language: node_js
 
branches:
  only:
    - publish_wd
 
env:
  global:
    - URL="https://raw.githack.com/w3c/pub-manifest/publish_wd/snapshot/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-08-19-pwg#resolution3"
    - secure: "IDtRhkSBPyIWwRA5fiW/8r2cENHQTZTqUxl1FjgJi9u2VTj9bJ4y5RWcfSImIm+pmOQKD0GonOffFRs1XjZiLS2Z8pTJZSTwQbjoB0ArWV604KqWLtydlOSX5kaMg033SHVbMdgjk1ooXHU2gnlPAO59D3RkZtR/+QHDMyJBcjHvKlSn+qKqwCNs+HeBvxuJgaR7CnDtJ8L9SuE7aC29kShW2sHNyVslEtBnTXKCHc619bS2LrGkCB0zrH45Oi9lU9h8QNApu9JRv6HbFX3/9OZ3wcpLFVfICwxwfFp44iiPaAH/0yIL1i2+vVsmfggsJoG/FyeSi3juwpaee8A7ZnhO09mAs33fBGY8n17Z/6hGRp5LODc2El3K4nlQC+DMRxNI0Fug4LOJLEjHjKKGW3BWKTefs7q1gQRpR+tMG3yW8AXT4YSpsm5+V27a5n986wUVA7HZz4fC00g1fja3PM3iX11mPZsdmb8CMcAOYDSOZwPOaWLPIUDSIJArK2WZIq8qB/sdjjSr6V59NZXOsMPohbBxsuRatfE20IgXp4KUHlUDLHVcJQx9poQC9cqljVSHgynMikXGsvj+lhkChUKNZEXo6wrKF+OkPsDLi9RsMFpmR4Ovyj1EBBFtHS0yCIVc6a+XtcPQ9B9Dc7sDkDDMhtLdEG5/98HbnvQPC6w="
 
script:
  - echo "ok"
 
after_success:
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
